import SwiftUI

// Auto-generated by Last Mile - do not edit manually
enum AppConfig {
    static let primaryColor    = Color(hex: "#EF4444")
    static let accentColor     = Color(hex: "#F97316")
    static let backgroundColor = Color(hex: "#FFFFFF")
    static let fontDesign: Font.Design = .rounded
    static let preferredColorScheme: ColorScheme? = nil
    static let storeName       = "متجري"
    static let storeTagline    = "أفضل المنتجات"
    static let storeCurrency   = "ر.س"
    static let products: [(name: String, emoji: String, price: String)] = [
        ("سماعات لاسلكية", "🎧", "149"),
        ("حافظة هاتف",     "📱", "49"),
        ("شاحن سريع",      "⚡", "89"),
        ("عرض خاص",        "🎁", "199"),
    ]
}
